### ISSUE TITLE
Update alt text for all images

### ISSUE THREAD

**Issue by astrogeco** [GSA-TTS/identity-idva-docs#69]
Per guidance from TTS accessibility guild. 

```[tasklist]
### Tasks
- [x] Remove alt-text from all "decorative" home-page images by setting attribute to `alt=""`
- [x] Add alt text for study steps illustration on landing page. See below or the [🔒 landing page content document](https://docs.google.com/document/d/1kNxmPnv7uSaYfnRuB7pnM2R2QDVsQcooNCoS0x1yFrg/edit#)
- [x] Add alt text for study steps illustration on FAQ page
```

Alt text for each "study steps" image. Update
1.  `Person registering for the study using a mobile device.`
2. `Person using their smartphone take a picture of their government issued identification.`
3. `Person using their smartphone to take a selfie.`
4. `People taking multiple selfies and pictures of their government ID`
5. `Person inputting information on their smartphone.`
6. `Person receiving a notification of their compensation gift card on their phone.`
